# 1- Create 3*3 array of diagonal nines


In [1]:
import numpy as np

In [2]:
x = np.eye(3)*9
print(x)

[[9. 0. 0.]
 [0. 9. 0.]
 [0. 0. 9.]]


# 2- create 4*4 array get even numbers from 2 to 32 and use boolen to pick up values that is .5 standard diviasion of the mean

In [3]:
y = np.arange(2, 33, 2).reshape(4, 4)
print(y)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [4]:
std_y = np.std(x)
#print(std_y)
#print(.5*std_y)
#print(int(.5*std_y))
mean_y = np.mean(y)
#print(mean_y)

In [5]:
#We Want Values of mean +- (0.5*STD)
values = y[(y > (mean_y - (0.5*std_y))) & (y < (mean_y + (0.5*std_y)))] 
print(values)

[16 18]


# 3- Create 3*3 array That Contains Only Zeros Of type int

In [6]:
z = np.zeros((3,3), dtype=int)
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


# 4- Ask The User For a number, then use BroadCasting to create a n*n array that has first colums full af ones,second colums full af twos, etc...

In [7]:
n = int(input("Enter a number : "))
print(n)

Enter a number : 5
5


In [8]:
w = np.ones((n,n))
print(w)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
q = np.arange(0,n)
print(q)

[0 1 2 3 4]


In [10]:
print(w+q)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]
